### ISSUE TITLE
Add branch correction utilities for committing under the wrong author

### ISSUE THREAD

**Issue by vermiculus** [tarsius/magit-rockstar#1]
From [Gitter](https://gitter.im/magit/magit?at=59958efe614889d4755a1278):

> Matus Goljer @Fuco1 Aug 17 07:41
Hi. Is there some way to change all the commits on a branch to a different author? I've commited under the wrong identity 
The only way I can do this right now is to cherry pick the commits one by one and commit while -R (reclaiming the author) which is rather annoying
>
> Sean Allred @vermiculus Aug 17 07:50
@Fuco1 I'm no expert, but it sounds like a job for filter-branch, yes?
>
> Matus Goljer @Fuco1 Aug 17 07:57
@vermiculus Thanks for the reply, I should've maybe pointed out I'm asking about a Magit solution 
some magical three keystroke super feature 
>
> Sean Allred @vermiculus Aug 17 07:59
@Fuco1 Point being that if Magit has any filter-branch functionality, that'd be where I'd start looking 
>
> Dan Davison @dandavison Aug 17 08:00
It looks like not yet? magit/magit#2849
>
> Sean Allred @vermiculus Aug 17 08:00
Perhaps https://github.com/tarsius/magit-rockstar/ can be enhanced with this functionality.

Since this repository is already using `filter-branch` and manipulating commit data, it might make sense to provide this functionality here.

**Comment by tarsius** [comment]
It might. But someone other than me would have to implement it.

**Comment by tarsius** [comment]
In other words, I am closing this because I have no intention of implementing it. (Not that it wouldn't be useful, but there are so many things I still have to do that are much more useful.)
